# Hosting for web app
[build]
  base = "/"
  command = "REACT_APP_API_STAGE=dev npm run ci:frontend"
  publish = "packages/webapp/build/"

[context.production]
  command = "REACT_APP_API_STAGE=prod npm run ci:frontend"

# Always redirect any request to our index.html and return the status code 200.
[[redirects]]
  from    = "/*"
  to      = "/index.html"
  status  = 200