service: warm-and-fuzzy-api

plugins:
  - serverless-webpack
  - serverless-offline

provider:
  name: aws
  runtime: nodejs10.x
  region: us-west-2

functions:
  apiGetConfig:
    handler: api/v1/getConfig/handler.getConfig
    events:
      - http:
          method: get
          path: api/v1/getConfig
