# c.f. https://circleci.com/docs/2.0/language-javascript/
version: 2.1

executors:
  grumpy-executor:
    docker:
      - image: grumpycorp/warm-and-fuzzy-ci:10
    working_directory: ~/warm-and-fuzzy

jobs:
  #
  # cloud+firmware jobs
  #

  build:
    executor: grumpy-executor
    steps:
      # Check out source
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}

      # Install dependencies
      - run: npm install

      # Save cache
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      # Run builds
      - run:
          name: Build
          command: |
            if [ "$CIRCLE_BRANCH" == "master" ]; then
              REACT_APP_API_STAGE=prod npm run build
            else
            npm run build -ws
            fi
          environment:
            # Limit NodeJS heap size so we don't OOM
            NODE_OPTIONS: --max_old_space_size=1500

      # Run tests
      - run: npm run test -ws

      # Run lint
      - run: npm run lint -ws

      # Persist workspace for deployment
      - persist_to_workspace:
          root: .
          paths:
            - packages

  cloud-deploy:
    executor: grumpy-executor
    steps:
      # Check out source
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}

      # Attach to `build` workspace (provides built packages/)
      - attach_workspace:
          at: .

      # Install dependencies
      - run: npm install
      - run: npm run bootstrap

      # (Don't save cache again, we'll just let `build` deal with it)

      # Configure AWS CLI
      - run: aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
      - run: aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
      - run: aws configure set region $AWS_DEFAULT_REGION

      # Deploy
      - run:
          name: Deploy
          command: |
            if [ "$CIRCLE_BRANCH" == "master" ]; then
              npm run deploy:prod
            else
              npm run deploy:dev
            fi

  firmware-deploy:
    executor: grumpy-executor
    steps:
      # Check out source
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}

      # Attach to `build` workspace (provides built packages/)
      - attach_workspace:
          at: .

      # Install dependencies
      - run: npm install
      - run: npm run bootstrap

      # (Don't save cache again, we'll just let `build` deal with it)

      # Upload firmware to Particle cloud
      - run:
          name: Upload firmware to Particle
          command: npm run deploy-firmware:prod

#
# Workflows
#

workflows:
  cloud-and-firmware:
    jobs:
      - build:
          context: warm-and-fuzzy-particle
      - hold-to-deploy-cloud:
          type: approval
          requires:
            - build
      - cloud-deploy:
          context: warm-and-fuzzy-aws
          requires:
            - hold-to-deploy-cloud
      - hold-to-deploy-firmware:
          type: approval
          requires:
            - build
          filters:
            branches:
              only: master
      - firmware-deploy:
          context: warm-and-fuzzy-particle
          requires:
            - hold-to-deploy-firmware
          filters:
            branches:
              only: master
