Resources:
  ValueStreamsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ${self:custom.dynamoDbTablePrefix}ValueStreams
      KeySchema:
        # Partition key
        - AttributeName: stream
          KeyType: HASH
        # Sort key
        - AttributeName: ts
          KeyType: RANGE
      AttributeDefinitions:
        # Partition key
        - AttributeName: stream
          AttributeType: S
        # Sort key
        - AttributeName: ts
          AttributeType: N
      BillingMode: PAY_PER_REQUEST
