Resources:
  LatestSensorValuesTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ${self:custom.dynamoDbTablePrefix}LatestSensorValues
      KeySchema:
        # Partition key
        - AttributeName: tenant
          KeyType: HASH
        # Sort key
        - AttributeName: id
          KeyType: RANGE
      AttributeDefinitions:
        # Partition key
        - AttributeName: tenant
          AttributeType: S
        # Sort key
        - AttributeName: id
          AttributeType: S
      BillingMode: PAY_PER_REQUEST
