Resources:
  ThermostatConfigurationTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ${self:custom.dynamoDbTablePrefix}ThermostatConfiguration
      KeySchema:
        # Partition key
        - AttributeName: tenant
          KeyType: HASH
        # Sort key
        - AttributeName: id
          KeyType: RANGE
      AttributeDefinitions:
        # Partition key
        - AttributeName: tenant
          AttributeType: S
        # Sort key
        - AttributeName: id
          AttributeType: S
      BillingMode: PAY_PER_REQUEST
      StreamSpecification:
        StreamViewType: NEW_AND_OLD_IMAGES
