Resources:
  SensorConfigTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ${self:custom.dynamoDbTablePrefix}SensorConfig
      KeySchema:
        # Partition key
        - AttributeName: tenant
          KeyType: HASH
        # Sort key
        - AttributeName: sensorId
          KeyType: RANGE
      AttributeDefinitions:
        # Partition key
        - AttributeName: tenant
          AttributeType: S
        # Sort key
        - AttributeName: sensorId
          AttributeType: S
      BillingMode: PAY_PER_REQUEST
