Resources:
  DeviceTenancyTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ${self:custom.dynamoDbTablePrefix}DeviceTenancy
      KeySchema:
        # Partition key
        - AttributeName: deviceId
          KeyType: HASH
      AttributeDefinitions:
        # Partition key
        - AttributeName: deviceId
          AttributeType: S
      BillingMode: PAY_PER_REQUEST
